Models/ErrorViewModel.cs
namespace Vaulted_Reborn.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ViewModels/CharacterViewModel.cs
using Vaulted_Reborn.Controllers;
using VaultedBLL.Models;

namespace Vaulted_Reborn.ViewModels
{
    public class CharacterViewModel
    {

        public List<CharacterDropdownItems> CharacterNames { get; set; }
        public Character Character { get; set; }

        public CharacterViewModel(List<CharacterDropdownItems> characterNames, Character character)
        {
            CharacterNames = characterNames;
            Character = character;
        }
    }

}

Controllers/CharacterController.cs
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using Org.BouncyCastle.Tls;
using System.Diagnostics;
using System.Security.Cryptography.X509Certificates;
using Vaulted_Reborn.ViewModels;
using VaultedBLL;
using VaultedBLL.Models;
using VaultedDAL;
using VaultedDAL.NewFolder;

namespace Vaulted_Reborn.Controllers
{
	public class CharacterController : Controller
	{
		private readonly CharacterService _characterService;

		public CharacterController()
		{
			_characterService = new CharacterService();
		}

        public async Task<IActionResult> Index(int id)
        {
            Character character = await _characterService.GetCharacter(id != 0 ? id : 2);
			List<CharacterDropdownItems> charnames = await _characterService.GetCharacterNames(1);

			var viewModel = new CharacterViewModel(charnames, character);

            return View("Character", viewModel);
        }

        public async Task<Character> LoadCharacter(int id)
        {
            Character character = await _characterService.GetCharacter(id);
             return character;
        }

        [HttpPost]
        public async Task<IActionResult> SaveChanges([FromBody] Character model)
        {
            var character = await _characterService.GetCharacter(model.Id);

            character.Race = model.Race;
            character.Subclass = model.Subclass;
            character.Class = model.Class;
            character.Level = model.Level;
            character.MaxHP = model.MaxHP;
            character.HP = model.HP;
            character.AC = model.AC;
            character.Speed = model.Speed;
            character.Strength = model.Strength;
            character.Dexterity = model.Dexterity;
            character.Constitution = model.Constitution;
            character.Intelligence = model.Intelligence;
            character.Wisdom = model.Wisdom;
            character.Charisma = model.Charisma;

            await _characterService.SaveChanges(character);

            return Ok(character);
        }

        public IActionResult Creator()
        {
            return View();
        }

        public async Task<IActionResult> CharacterList()
        {
            List<Character> characters = await _characterService.GetCharacters(1);

            return View("CharacterList", characters);
        }

        public async Task<IActionResult> CreateCharacter(Character character)
        {
            await _characterService.CreateCharacter(character);

            return RedirectToAction("CharacterList");
        }

        public async Task<IActionResult> DeleteCharacter(int id)
        {
            await _characterService.DeleteCharacter(id);

            return Ok();

        }



    }
}

Controllers/CharacterSheetController.cs
using Microsoft.AspNetCore.Mvc;

namespace Vaulted_Reborn.Controllers
{
	public class CharacterSheetController : Controller
	{
		public IActionResult CharacterSheet()
		{
			return View("CharacterSheet");
		}
	}
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Vaulted_Reborn.Models;

namespace Vaulted_Reborn.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PlayerController.cs
using Microsoft.AspNetCore.Mvc;
using VaultedDAL;
using VaultedBLL;

namespace Vaulted_Reborn.Controllers
{
    public class PlayerController : Controller
    {
        public IActionResult LoginPage()
        {
            return View("Login");
        }
        public IActionResult RegisterPage()
        {
            return View("Register");
        }


        private readonly PlayerService _playerService;

        public PlayerController()
        {

            _playerService = new PlayerService(new PlayerDAO());
        }

        [HttpPost]
        public IActionResult Login(string email, string password)
        {
            if (_playerService.Authenticate(email, password))
            {            
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.ErrorMessage = "Incorrect email or password";
                return View();
            }
        }

        [HttpPost]
        public IActionResult Register(string email, string password)
        {
            if (_playerService.Register(email, password))
            {
                return RedirectToAction("Index", "Auth");
            }
            return View();
        }
    }
}

Controllers/SpellController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Vaulted.Models;
using VaultedBLL;
using VaultedDAL;

namespace Vaulted_Reborn.Controllers
{
    public class SpellController : Controller
    {
        private readonly SpellService _spellService;

        public SpellController()
        {
            _spellService = new SpellService(new SpellApi());
        }

        public async Task<IActionResult> Index()
        {
            string jsondata = await _spellService.GetSpellList();
            SpellList spellList = JsonConvert.DeserializeObject<SpellList>(jsondata);
            if (spellList != null)
            {
                return View(spellList);
            }
            
            return View();
           
        }
    }
}

Views/Character/Character.cshtml
<div class="character-container">
    <div class="character-content">
    <div class="top-row">
        <div class="name-details-container">

                <select id="char-select" onchange="UpdateCharacter(this.value)">
                @foreach( var character in @Model.CharacterNames){
                        <option value="@character.Id">@character.Name</option>

                }   
                </select>
                <div class="character-details">
                    <p class="race" contenteditable="true">@Model.Character.Race </p>
                    <p class="subclass" contenteditable="true">@Model.Character.Subclass </p>
                    <p class="class" contenteditable="true"> @Model.Character.Class </p>, Level
                    <p class="level" contenteditable="true">@Model.Character.Level</p>
                </div>
        </div>
            <a onclick="SaveChanges()"><i class="fa-regular fa-save top-icons"></i></a>
            <a onclick="DeleteCharacter()"><i class="fa-regular fa-trash-can top-icons"></i></a>


    </div>
    <div class="second-row">
        <div class="avatar-container">
            <img class="avatar" src="@Url.Content("/Assets/tiefling-cleric.jpg")" alt="Character Avatar">
        </div>
        <div class="stats-container">
            <div class="stat">
                    <p class="stat-value" >@Model.Character.AC</p>
                <p class="stat-label">AC</p>
            </div>
            <div class="stat">
                    <p class="stat-value">@Model.Character.Speed</p>
                <p class="stat-label">Speed</p>
            </div>
            <div class="stat">
                    <p class="stat-value">+@Model.Character.ProficiencyBonus</p>
                <p class="stat-label">Prof</p>
            </div>
            <div class="stat">
                    <p class="stat-value">@((Model.Character.Dexterity) - 10 >> 1)</p>
                <p class="stat-label">Initiative</p>
            </div>
        </div>
    </div>
   <div class="health-slider-container">
            <input class="health-slider" type="range" min="0" max="@Model.Character.MaxHP" value="@Model.Character.HP" disabled />
       <img class="health-icon"  src="@Url.Content("Assets/heart.png")"/>
            <div class="health-text"><p class="hp" contenteditable="true">@Model.Character.HP</p>/<p class="maxhp" contenteditable="true">@Model.Character.MaxHP</p></div>
   </div>

    <div class="input-squares-container">
        <div class="input-square">
                <input type="number" class="abilityscore" id="str" name="str" min="1" max="20" value="@Model.Character.Strength">
            <label for="str">Str</label>
        </div>
        <div class="input-square">
                <input type="number" class="abilityscore" id="dex" name="dex" min="1" max="20" value="@Model.Character.Dexterity">
            <label for="dex">Dex</label>
        </div>
        <div class="input-square">
                <input type="number" class="abilityscore"  id="con" name="con" min="1" max="20" value="@Model.Character.Constitution">
            <label for="con">Con</label>
        </div>
        <div class="input-square">
                <input type="number" class="abilityscore"  id="int" name="int" min="1" max="20" value="@Model.Character.Intelligence">
            <label for="int">Int</label>
        </div>
        <div class="input-square">
                <input type="number" class="abilityscore"  id="wis" name="wis" min="1" max="20" value="@Model.Character.Wisdom">
            <label for="wis">Wis</label>
        </div>
        <div class="input-square">
                <input type="number" class="abilityscore"  id="cha" name="cha" min="1" max="20" value="@Model.Character.Charisma">
            <label for="cha">Cha</label>
        </div>
    </div>
    <div class="skill-container">
        <div class="sixth-row">
            <div class="third underline">
                    <i class="fa-solid fa-person-running char-ul-icon"></i>
            </div>
            <div class="third">
                <i class="fa-solid fa-wand-magic char-ul-icon"></i>
            </div>
            <div class="third">
                <i class="fa-solid fa-shield-halved char-ul-icon"></i>
            </div>
        </div>
    @for (int i = 0; i < 5; i++)
    {
            <div class="item-row">
                <div class="checkbox">
                    <input type="checkbox" id="skill1" name="skill1" class="skill-checkbox-input">
                    <label for="skill1"></label>
                </div>
                <div class="skill-name">
                    <p>Acrobatics</p>
                </div>
                <div class="skill-abbr">
                    <p>DEX</p>
                </div>
                <div class="skill-bonus">
                    <input type="number" id="skill1-bonus" name="skill1-bonus" value="0" min="-999" max="999" step="1">
                </div>
            </div>
        }
    
        </div>
    </div>

   
    @section scripts{
        <script>
            document.getElementById('char-select').value = @Model.Character.Id;
            
            const thirdDivs = document.querySelectorAll('.third');

            document.querySelectorAll('.char-ul-icon').forEach(e => e.addEventListener('click', () => {
                thirdDivs.forEach(div => div.classList.remove('underline'));
                e.parentNode.classList.add('underline');
                console.log("hit");
            }))


            function UpdateCharacter(id){
                
                console.log("arrived at function");

                $.ajax({
                    url: '/Character/LoadCharacter',
                    data: { id: id },
                    type: 'GET',
                    success: function (e) {
                        console.log(e);
                        document.querySelector(".race").textContent = e.race;
                        document.querySelector(".subclass").textContent = e.subclass;
                        document.querySelector(".class").textContent = e.class;
                        document.querySelector(".level").textContent = e.level;

                        var charhp = document.querySelector(".health-slider");
                        charhp.max = e.maxHP;
                        charhp.value = e.hp;
                        document.querySelector(".health-text").textContent = e.hp + "/" +e.maxHP

                        var stats = document.querySelectorAll(".stat-value");
                        stats[0].textContent = e.ac;
                        stats[1].textContent = e.speed;
                        stats[2].textContent = "+" + e.proficiencyBonus;
                        stats[3].textContent = "+" + (e.dexterity - 10) >> 1;
                        var as = document.querySelectorAll(".abilityscore");
                        as[0].value = e.strength;
                        as[1].value = e.dexterity;
                        as[2].value = e.constitution;
                        as[3].value = e.intelligence;
                        as[4].value = e.wisdom;
                        as[5].value = e.charisma;
                    },
                    error: function (err) {
                        console.log(err)
                    }
                });
            }

            function DeleteCharacter(){
                var select = document.querySelector("#char-select")

                $.ajax({
                    url: '/Character/DeleteCharacter',
                    data: { id: select.value},
                    type: 'POST',
                    success: function () {
                        UpdateCharacter(1)
                        select.value = 1
                    },
                    error: function () {
                        alert("An error occurred while deleting the character.");
                    }
                });
            }

            function SaveChanges() {
                var select = document.querySelector("#char-select")
                var character = {
                    id: select.value,
                    race: document.querySelector(".race").textContent.trim(),
                    subclass: document.querySelector(".subclass").textContent.trim(),
                    class: document.querySelector(".class").textContent.trim(),
                    level: document.querySelector(".level").textContent.trim(),
                    maxHP: document.querySelector(".maxhp").textContent.trim(),
                    hp: document.querySelector(".hp").textContent.trim(),
                    ac: document.querySelectorAll(".stat-value")[0].textContent.trim(),
                    speed: document.querySelectorAll(".stat-value")[1].textContent.trim(),
                    strength: document.querySelectorAll(".abilityscore")[0].value,
                    dexterity: document.querySelectorAll(".abilityscore")[1].value,
                    constitution: document.querySelectorAll(".abilityscore")[2].value,
                    intelligence: document.querySelectorAll(".abilityscore")[3].value,
                    wisdom: document.querySelectorAll(".abilityscore")[4].value,
                    charisma: document.querySelectorAll(".abilityscore")[5].value
                };

                console.log(character);

                $.ajax({
                    url: '/Character/SaveChanges',
                    data: JSON.stringify(character),
                    type: 'POST',
                    contentType: 'application/json',
                    success: function (response) {
                        UpdateCharacter(select);
                    },
                    error: function (error) {
                        console.log(error)
                    }
                });
            }

        </script>
    }

   
</div>

Views/Character/CharacterList.cshtml
<div class="character-container">
    <div class="character-content">
        <h2>Characters</h2>
        <ul style="list-style: none">
            @foreach (var character in @Model)
            {
                <li >
                    <div class="clist-card" data-character-id="@character.Id" onclick="location.href='@Url.Action("Index", "Character", new { id = character.Id })'">
                        <div class="clist-avatar">R</div>
                        <div class="clist-info">
                            <div class="row">@character.Name</div>
                            <div class="row">@character.Class @character.Level</div>
                        </div>
                    </div>
                </li>
            }
           
        </ul>
    </div>
</div>


    @section scripts{
        <script>
           
        </script>
    }


    </div>

Views/Home/Index.cshtml
<div class="menu-wrapper">
		@*<div class="toggle-menu" onclick="toggleMenu()"><i class='bx bx-plus' ></i></div>*@
	<img  id="logo" onclick="toggleMenu()" src="@Url.Content("/Assets/Vaultednewsmall.png")" />

		<ul class="menu">
			<li style="--i: 1;">
			<a asp-area="" asp-controller="Character" asp-action="Creator">
					<i class="fa-sharp fa-solid fa-plus"></i>
				<p class="icon-label">Create Character</p>

				</a>
			</li>
			<li style="--i: 2;">
				<a asp-area="" asp-controller="Character" asp-action="CharacterList">
				<i class="fa-sharp fa-solid fa-list"></i>
				<p class="icon-label">Character List</p>

			</a>
			</li>
			<li style="--i: 3;">
			<a asp-area="" asp-controller="Character" asp-action="Index">
				<i class="fa-sharp fa-solid fa-pen-to-square"></i>
				<p class="icon-label">Character</p>

			</a>
			</li>
			<li style="--i: 4;">
				<a href="#">
					<i class='bx bxs-doughnut-chart' ></i>
				</a>
			</li>
			<li style="--i: 5;">
				<a href="#">
					<i class='bx bxs-message-dots' ></i>
				</a>
			</li>
			<li style="--i: 6;">
			<a asp-area="" asp-controller="Spell" asp-action="Index">
				<i class="fa-solid fa-wand-magic-sparkles"></i>
				<p class="icon-label">Spells</p>

			</a>
			</li>
		</ul>
	</div>




@section scripts {
        <script>
		function toggleMenu() {
			document.querySelector('.menu-wrapper').classList.toggle('active');
		}
        </script>
}



    

Views/Player/Login.cshtml
@{
    ViewData["Title"] = "Login Page";
}
<div class="bg-cover"></div>
<section class="login-section">
    <div class="form-box">
        <div class="form-value">

            <form action="@Url.Action("Login", "Player")" method="post">

                @*<img id="login-logo" src="@Url.Content("/Assets/Vaultednew.png")" />*@



                @if (ViewBag.ErrorMessage != null)
                {
                    <div class="alert alert-danger">
                        @ViewBag.ErrorMessage
                    </div>
                }
                <div class="inputbox">
                    <input type="email" name="email" placeholder="Email" required>

                </div>
                <div class="inputbox">
                    <input type="password" name="password" placeholder="Password" required>

                </div>
                <div class="forget">
                    <label for=""><input type="checkbox" name="remember" value="True">Remember Me</label>

                </div>

                <button class="login">Log in</button>
                <div class="register">

                    <p><a href="#">Forgot Password?</a></p>
                    <p>Don't have a account <a href="@Url.Action("RegisterPage", "Player")">Register</a></p>
                </div>
            </form>
        </div>
    </div>
</section>

Views/Player/Register.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="bg-cover"></div>

<div class="login-wrapper">
    <section class="login-section">
        <div class="form-box">
            <div class="form-value">

                <form action="@Url.Action("Register", "Player")" method="post">
                    @*<img id="login-logo" src="@Url.Content("/Assets/Vaultednew.png")" />*@


                    <div class="inputbox">
                        <input type="email" name="email" placeholder="Email" required>
                    </div>
                    <div class="inputbox">
                        <input type="password" name="password" placeholder="Password" required>
                    </div>

                    <button class="login">Create Account</button>

                </form>
            </div>
        </div>
    </section>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vaulted_Reborn</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Vaulted_Reborn.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
   @* <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Vaulted_Reborn</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Spell" asp-action="Index">Spells</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="LoginPage">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>*@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/main.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Spell/Index.cshtml
  <ul id="data" class="list-group list-group-flush spell-list">
            @foreach (var spell in Model.results)
            {
                <li>             
                    <img class="spell-school-icon" src="@Url.Content("/Assets/spellschools/"+@spell.school+".png")">

                    <p>@spell.name</p>
                    <p>@spell.level.Split("-")[0] &nbsp</p>
                    <p>@spell.school</p>
                    <p>@spell.components</p>
                    <p>@spell.casting_time</p>
                    <p>@spell.range</p>
                </li>
            }
   </ul>